spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.0.40:3306/mapper-extend?allowPublicKeyRetrieval=true&allowMultiQueries=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: mapper
    password: jh@123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat,wall
    initial-size: 3
    min-idle: 1
    max-active: 20
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    validation-query: select 'x'
    max-wait: 6000
    pool-prepared-statements: true
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 60000
    web-stat-filter:
      enabled: true
      url-pattern: "/*"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  default-statement-timeout: 3000
  basePackage: cn.org.opendfl.mysql
  mapperLocations: classpath:mappers/*/*.xml
  config-location: classpath:mybatis-config.xml
  #表的id属性名
  idField: id
  #表数据创建时间属性名
  createTimeField: create_time
  #表数据修改时间属性名
  updateTimeField: modify_time



# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    info:
      enabled: true


logging:
  level:
    root: INFO
    cn:
      org:
        opendfl: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(-){faint} %clr([%14.14t]){faint} %clr(%-40.40logger.%13.13M){cyan} %clr(%3.3L) %clr(:){faint} %msg%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

